export const HEADER_MAX_HEIGHT = 60;
export const HEADER_MIN_HEIGHT = 52;
export const HEADER_ANIMATION_CONFIG = {
  HEADER_MAX_HEIGHT,
  HEADER_MIN_HEIGHT,
  ANIMATION_MAX_RANGE: 120,
  HEADER_SCROLL_DISTANCE: HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT,
};