export {default as DiscoveryBanner} from './banner'
export {default as DiscoveryNearByRestaurant} from './near-by-restaurant'
export {default as DiscoveryGrocery} from './grocery'
export {default as DiscoveryRecentOrderRestaurants} from './recent-order-restaurant'
export {default as DiscoveryMostOrderRestaurants} from './most-order-restaurant'
export {default as DiscoveryTopGroceriesPick} from './top-groceries-pick'
export {default as DiscoveryOurBrands} from './our-brands'
export {default as DiscoveryTopRatedRestaurants} from './top-rated-restaurants'
export {default as DiscoveryTopRatedGroceries} from './top-rated-groceries'
export { default as DiscoveryShopTypes } from './shop-types'
export { default as DiscoveryCartHeaderWithTabs } from './cart/DiscoveryCartHeaderWithTabs'
export { default as DiscoveryCartTabContent } from './cart/DiscoveryCartTabContent'
export { default as DiscoveryCartItem } from './cart/DiscoveryCartItem'